# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest # ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run a multi-line script
      run: |
        # echo Add other actions to build,
        # echo test, and deploy your project.
        # docker run -v $GITHUB_WORKSPACE:/src cdrx/pyinstaller-windows:latest 'pyinstaller --onefile -w --icon=.\\img\\icon.ico STDF_Reader_GUI.py'
        # sudo zip -r $GITHUB_WORKSPACE/dist/STDF_Reader_GUI.zip $GITHUB_WORKSPACE/dist/STDF_Reader_GUI.exe
        pyinstaller --onefile --icon=.\\img\\icon.ico STDF_Reader_GUI.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: STDF_Reader_GUI
        path: dist/
